//! Build-time shader compilation.
//!
//! Runs `wyn compile` for each Wyn root, emitting SPIR-V (+ a `.json` pipeline
//! descriptor) into OUT_DIR, and generates `shaders.rs` — a table that embeds
//! each `.spv` via `include_bytes!`. The driver `include!`s that table, so at
//! runtime it does NO shader file I/O and never shells out to `wyn`.
//!
//! TODO(build-validation): diff the `app.rs` GRAPH against each emitted `.json`
//! descriptor here and fail the build on drift.

use std::path::PathBuf;
use std::process::Command;

// Wyn entry roots to compile+embed. (key, path-relative-to-repo-root.) Library
// modules they `import` are pulled in by the compiler automatically.
const ROOTS: &[(&str, &str)] = &[("main", "wyn/main.wyn")];

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo = manifest.parent().expect("driver crate has a parent").to_path_buf();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", repo.join("wyn").display());

    let mut table = String::from(
        "// generated by build.rs — embedded SPIR-V modules\n\
         pub static SHADER_MODULES: &[(&str, &[u8])] = &[\n",
    );

    for (key, rel) in ROOTS {
        let src = repo.join(rel);
        let spv = out_dir.join(format!("{key}.spv"));
        let status = Command::new("wyn")
            .args(["compile", "--single-stage"])
            .arg(&src)
            .arg("-o")
            .arg(&spv)
            .status()
            .unwrap_or_else(|e| panic!("failed to run `wyn compile` ({e}); is `wyn` on PATH?"));
        assert!(status.success(), "`wyn compile {}` failed", src.display());

        // include_bytes! resolves env!("OUT_DIR") in the driver crate's own
        // compile context (same OUT_DIR), so the path stays machine-portable.
        table.push_str(&format!(
            "    ({key:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{key}.spv\"))),\n"
        ));
    }

    table.push_str("];\n");
    std::fs::write(out_dir.join("shaders.rs"), table).expect("write shaders.rs");
}
